#!/bin/bash

################-> are comments
################-> "#PBS" are Batch Script commands

#PBS -m abe

################ Verbose mode

#PBS -V

################

################ Change these parameters according to your requisites

#PBS -l nodes=1:ppn=24:cluster-Plumes,walltime=60:00:00

################ Where:
################ nodes = number of nodes requested
################ ppn = number of cores per node
################ cluster-Atlantica / cluster-Gates = cluster name
################ walltime = max allocation time

################ Please, change this e-mail address to yours

#PBS -M bruno.farenzena@gmail.com

################

#PBS -r n

################ Output options

#PBS -j oe

################

################ Please, change this directory to your working dir.

#PBS -d  /damarea/Bruno/LR_Re8950/scriptPost

################

################
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo `cat $PBS_NODEFILE | uniq > nodefile`
echo
echo JOB_ID:
echo `echo $PBS_JOBID`
echo ################

###############################
#cp /plumesarea/logger.sh ./   
#./logger.sh > shell.out.log & 
###############################
#ulimit -s unlimited
#ulimit -c unlimited
#export I_MPI_SHM_LMT=shm

#make

#mpirun -hostfile nodefile -np 96 ./incompact3d > log.out
#python pBackNew.py
#python dataProcessing.py
python dataAquis.py
################

echo Final Time is `date`

